# Header

menu:
  ä¸»é¡µ: /
  ç›¸å†Œ: /photos
  å½’æ¡£: /archives


love_time:
  mname: 'zw'
  wname: 'wj'
  starttime: '2011-10-01 00:00:00'


# SubNav
subnav:
  github: "https://github.com/Ziven-n"
  weibo: "https://weibo.com/5646297969/profile?topnav=1&wvr=6&is_all=1"
  #rss: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  bilibili: "https://space.bilibili.com/28764008/#/"
  #acfun: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  twitter: "https://twitter.com/Ziven233"
  #linkedin: "#"

rss: /atom.xml

# æ˜¯å¦éœ€è¦ä¿®æ”¹ root è·¯å¾„
# å¦‚æœæ‚¨çš„ç½‘ç«™å­˜æ”¾åœ¨å­ç›®å½•ä¸­ï¼Œä¾‹å¦‚ http://yoursite.com/blogï¼Œ
# è¯·å°†æ‚¨çš„ url è®¾ä¸º http://yoursite.com/blog å¹¶æŠŠ root è®¾ä¸º /blog/ã€‚
root: /

# Content

# æ–‡ç« å¤ªé•¿ï¼Œæˆªæ–­æŒ‰é’®æ–‡å­—
excerpt_link: 
# æ–‡ç« å¡ç‰‡å³ä¸‹è§’å¸¸é©»é“¾æ¥ï¼Œä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
show_all_link: 'å±•å¼€å…¨æ–‡'
# æ•°å­¦å…¬å¼
mathjax: false
# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: false

# æ‰“èµ
# æ‰“èµtypeè®¾å®šï¼š0-å…³é—­æ‰“èµï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰reward:trueå±æ€§ï¼Œæ‰æœ‰æ‰“èµï¼› 2-æ‰€æœ‰æ–‡ç« å‡æœ‰æ‰“èµ
reward_type: 2
# æ‰“èµwording
reward_wording: 'æ‰«ç åŠ å¥½å‹ğŸ˜„'
# æ”¯ä»˜å®äºŒç»´ç å›¾ç‰‡åœ°å€ï¼Œè·Ÿä½ è®¾ç½®å¤´åƒçš„æ–¹å¼ä¸€æ ·ã€‚æ¯”å¦‚ï¼š/assets/img/alipay.jpg
alipay: /img/alipay.png
# å¾®ä¿¡äºŒç»´ç å›¾ç‰‡åœ°å€
weixin: /img/wechat.png

# ç›®å½•
# ç›®å½•è®¾å®šï¼š0-ä¸æ˜¾ç¤ºç›®å½•ï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰toc:trueå±æ€§ï¼Œæ‰æœ‰ç›®å½•ï¼› 2-æ‰€æœ‰æ–‡ç« å‡æ˜¾ç¤ºç›®å½•
toc: 1
# æ ¹æ®è‡ªå·±çš„ä¹ æƒ¯æ¥è®¾ç½®ï¼Œå¦‚æœä½ çš„ç›®å½•æ ‡é¢˜ä¹ æƒ¯æœ‰æ ‡å·ï¼Œç½®ä¸ºtrueå³å¯éšè—hexoé‡å¤çš„åºå·ï¼›å¦åˆ™ç½®ä¸ºfalse
toc_hide_index: true
# ç›®å½•ä¸ºç©ºæ—¶çš„æç¤º
toc_empty_wording: 'ç›®å½•ï¼Œä¸å­˜åœ¨çš„â€¦'

# æ˜¯å¦æœ‰å¿«é€Ÿå›åˆ°é¡¶éƒ¨çš„æŒ‰é’®
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /icon.ico

#ä½ çš„å¤´åƒurl
avatar: /img/æ­£æ–¹å½¢ç‹—å¤´.png

#æ˜¯å¦å¼€å¯åˆ†äº«
share_jia: true

#è¯„è®ºï¼š1ã€å¤šè¯´ï¼›2ã€ç½‘æ˜“äº‘è·Ÿå¸–ï¼›3ã€ç•…è¨€ï¼›4ã€Disqusï¼›5ã€Gitment
#ä¸éœ€è¦ä½¿ç”¨æŸé¡¹ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰
#å…·ä½“è¯·å‚è€ƒwikiï¼šhttps://github.com/litten/hexo-theme-yilia/wiki/

#1ã€å¤šè¯´
duoshuo: false

#2ã€ç½‘æ˜“äº‘è·Ÿå¸–
wangyiyun: false

#3ã€ç•…è¨€
changyan_appid: true
changyan_conf: true

#4ã€Disqus åœ¨hexoæ ¹ç›®å½•çš„configé‡Œä¹Ÿæœ‰disqus_shortnameå­—æ®µï¼Œä¼˜å…ˆä½¿ç”¨yiliaçš„
disqus: false

#5ã€Gitment
gitment_owner: false      #ä½ çš„ GitHub ID
gitment_repo: 'mycomments'          #å­˜å‚¨è¯„è®ºçš„ repo
gitment_oauth:
  client_id: '29fd06ce2375b14338fe'           #client ID
  client_secret: '090b271a3e6ce6fae6fc80ce4d40e3ee14b671aa'       #client secret


#6ã€gitalkè¯„è®º
gitalk:
  enable:  true
  githubID:  Ziven-n   
  repo:  'mycomments'
  ClientID:  '29fd06ce2375b14338fe'
  ClientSecret:  '090b271a3e6ce6fae6fc80ce4d40e3ee14b671aa'
  adminUser:  Ziven-n
  distractionFreeMode: true


# æ ·å¼å®šåˆ¶ - ä¸€èˆ¬ä¸éœ€è¦ä¿®æ”¹ï¼Œé™¤éæœ‰å¾ˆå¼ºçš„å®šåˆ¶æ¬²æœ›â€¦
style:
  # å¤´åƒä¸Šé¢çš„èƒŒæ™¯é¢œè‰²
  header: '#4d4d4d'
  # å³æ»‘æ¿å—èƒŒæ™¯
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# sliderçš„è®¾ç½®
slider:
  # æ˜¯å¦é»˜è®¤å±•å¼€tagsæ¿å—
  showTags: false

# æ™ºèƒ½èœå•
# å¦‚ä¸éœ€è¦ï¼Œå°†è¯¥å¯¹åº”é¡¹ç½®ä¸ºfalse
# æ¯”å¦‚
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: 'æ–‡ç« æœç´¢ '
  friends: false
  aboutme: 'å…³äºæˆ‘'

friends:
  å‹æƒ…é“¾æ¥1: http://localhost:4000/
  å‹æƒ…é“¾æ¥2: http://localhost:4000/
  å‹æƒ…é“¾æ¥3: http://localhost:4000/
  å‹æƒ…é“¾æ¥4: http://localhost:4000/
  å‹æƒ…é“¾æ¥5: http://localhost:4000/
  å‹æƒ…é“¾æ¥6: http://localhost:4000/

aboutme: å¾ˆå¥½ï¼Œä½ æˆåŠŸå¼•èµ·äº†æˆ‘çš„æ³¨æ„ï½